name: Trips Build and Publish Image

env:
  build_name: Trips

on:
  push:
    branches:
      - main
    paths:
      - apis/trips/**
      - .github/workflows/trips-build.yml

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: apis/trips
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image
        uses: docker/build-push-action@v2.2.2
        with:
          push: true
          tags: docker.pkg.github.com/api-trips:${{ GITHUB_SHA }}
