name: Trips Build and Publish Image

env:
  build_name: Trips
  registry: docker.pkg.github.com
  repository: clarenceb/api-trips
  docker_path: ./apis/trips

on:
  push:
    branches:
      - main
    paths:
      - apis/trips/**
      - .github/workflows/trips-build.yml

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: apis/trips
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker build
        run: docker build -t $registry/$repository:${{github.run_number}} --build-arg build_version=${{github.run_number}} $docker_path

      - name: Docker push
        run: docker push $registry/$repository:${{github.run_number}}
